// SPDX-License-Identifier: AGPL-3.0-or-later

// src/tools/image_generate.rs

//! `image_generate` — turn a text prompt into an image via the OpenAI Images
//! API (or an OpenAI-compatible endpoint configured under `providers.openai`).
//!
//! The generated bytes are saved to the content-addressed [`ArtifactStore`] and
//! returned as a markdown image ref (`![alt](/api/artifacts/<sha>.png)`), which
//! the chat UI already renders inline with download/copy. No extra plumbing —
//! it rides the same artifact path as `code_run`'s plots.
//!
//! Network tier; enabled only when an OpenAI key resolves (config or
//! `OPENAI_API_KEY`). One provider for now (closes the "no image generation"
//! gap); other providers can follow the same shape.

use std::sync::Arc;
use std::time::Duration;

use async_trait::async_trait;
use base64::Engine as _;
use serde_json::{json, Value};
use tracing::info;

use super::{Tier, Tool, ToolArgs, ToolResult};
use crate::artifacts::ArtifactStore;
use crate::config::MiraConfig;
use crate::MiraError;

pub struct ImageGenerateTool {
    api_key: String,
    base_url: String,
    default_model: String,
    artifacts: Arc<ArtifactStore>,
    http: reqwest::Client,
}

impl ImageGenerateTool {
    /// Resolve the OpenAI key + endpoint from config (falling back to the
    /// `OPENAI_API_KEY` env var), and the shared artifact store.
    pub fn new(config: &MiraConfig, artifacts: Arc<ArtifactStore>) -> Self {
        let oa = &config.providers.openai;
        let api_key = oa
            .api_key
            .as_deref()
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .map(str::to_string)
            .unwrap_or_else(|| std::env::var("OPENAI_API_KEY").unwrap_or_default());
        let base_url = {
            let b = oa.base_url.trim().trim_end_matches('/');
            if b.is_empty() { "https://api.openai.com/v1".to_string() } else { b.to_string() }
        };
        let http = reqwest::Client::builder()
            .timeout(Duration::from_secs(120)) // image gen is slow; don't trip the default
            .build()
            .unwrap_or_default();
        Self { api_key, base_url, default_model: "dall-e-3".into(), artifacts, http }
    }
}

#[async_trait]
impl Tool for ImageGenerateTool {
    fn name(&self) -> &str {
        "image_generate"
    }

    fn description(&self) -> &str {
        "Generate an image from a text prompt and return it inline. Use for \
         illustrations, diagrams-as-art, mockups, icons, etc. Returns a markdown \
         image the user sees rendered (with download/copy). Not for editing an \
         existing image."
    }

    fn tier(&self) -> Tier {
        Tier::Network
    }

    fn enabled(&self) -> bool {
        !self.api_key.is_empty()
    }

    fn args_schema(&self) -> Value {
        json!({
            "type": "object",
            "required": ["prompt"],
            "properties": {
                "prompt": {
                    "type": "string",
                    "description": "Detailed description of the image to generate."
                },
                "model": {
                    "type": "string",
                    "description": "Image model (e.g. dall-e-3, gpt-image-1). Defaults to dall-e-3."
                },
                "size": {
                    "type": "string",
                    "enum": ["1024x1024", "1024x1792", "1792x1024", "512x512", "256x256"],
                    "description": "Image dimensions. Defaults to 1024x1024."
                }
            }
        })
    }

    async fn execute(&self, args: ToolArgs) -> Result<ToolResult, MiraError> {
        if self.api_key.is_empty() {
            return Ok(ToolResult::failure(
                "image_generate is unavailable — no OpenAI API key configured \
                 (set providers.openai.api_key or OPENAI_API_KEY).",
            ));
        }
        let Some(prompt) = args.get("prompt").and_then(Value::as_str).filter(|s| !s.trim().is_empty())
        else {
            return Ok(ToolResult::failure("image_generate: `prompt` is required."));
        };
        let model = args.get("model").and_then(Value::as_str).unwrap_or(&self.default_model);
        let size = args.get("size").and_then(Value::as_str).unwrap_or("1024x1024");

        // Build the request. gpt-image-1 always returns b64_json and rejects
        // `response_format`; dall-e-* needs it set to get bytes (vs a URL).
        let mut body = json!({ "model": model, "prompt": prompt, "n": 1, "size": size });
        if !model.starts_with("gpt-image") {
            body["response_format"] = json!("b64_json");
        }

        let resp = self
            .http
            .post(format!("{}/images/generations", self.base_url))
            .bearer_auth(&self.api_key)
            .json(&body)
            .send()
            .await
            .map_err(|e| MiraError::ToolError(format!("image_generate request failed: {e}")))?;

        let status = resp.status();
        let payload: Value = resp
            .json()
            .await
            .map_err(|e| MiraError::ToolError(format!("image_generate: bad response: {e}")))?;
        if !status.is_success() {
            let msg = payload
                .get("error")
                .and_then(|e| e.get("message"))
                .and_then(Value::as_str)
                .unwrap_or("unknown error");
            return Ok(ToolResult::failure(format!("image_generate API error ({status}): {msg}")));
        }

        let first = payload.get("data").and_then(|d| d.get(0));
        let bytes: Vec<u8> = if let Some(b64) = first.and_then(|d| d.get("b64_json")).and_then(Value::as_str) {
            base64::engine::general_purpose::STANDARD
                .decode(b64)
                .map_err(|e| MiraError::ToolError(format!("image_generate: bad base64: {e}")))?
        } else if let Some(url) = first.and_then(|d| d.get("url")).and_then(Value::as_str) {
            // Some endpoints only return a URL — fetch the bytes.
            self.http
                .get(url)
                .send()
                .await
                .map_err(|e| MiraError::ToolError(format!("image_generate: fetch image: {e}")))?
                .bytes()
                .await
                .map_err(|e| MiraError::ToolError(format!("image_generate: read image: {e}")))?
                .to_vec()
        } else {
            return Ok(ToolResult::failure("image_generate: response carried no image data."));
        };

        let id = self
            .artifacts
            .save_bytes(&bytes, "png")
            .map_err(|e| MiraError::ToolError(format!("image_generate: store artifact: {e}")))?;
        info!("image_generate: produced {} ({} bytes, model={model})", id.filename(), bytes.len());

        // The markdown ref renders inline; the revised-prompt line (dall-e-3
        // rewrites prompts) gives the model + user the actual prompt used.
        let mut out = id.markdown_image("Generated image");
        if let Some(revised) = first.and_then(|d| d.get("revised_prompt")).and_then(Value::as_str) {
            out.push_str(&format!("\n\n_Prompt used: {revised}_"));
        }
        Ok(ToolResult::success(out))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tool(key: Option<&str>) -> ImageGenerateTool {
        let dir = tempfile::tempdir().unwrap();
        let store = Arc::new(ArtifactStore::new(dir.path()).unwrap());
        let mut cfg = MiraConfig::default();
        cfg.providers.openai.api_key = key.map(str::to_string);
        // Avoid the env var leaking into the test from the dev shell.
        unsafe { std::env::remove_var("OPENAI_API_KEY") };
        ImageGenerateTool::new(&cfg, store)
    }

    #[test]
    fn disabled_without_key_enabled_with_key() {
        assert!(!tool(None).enabled());
        assert!(tool(Some("sk-test")).enabled());
    }

    #[test]
    fn schema_requires_prompt_and_tier_is_network() {
        let t = tool(Some("sk-test"));
        assert_eq!(t.name(), "image_generate");
        assert_eq!(t.tier(), Tier::Network);
        let schema = t.args_schema();
        assert_eq!(schema["required"][0], "prompt");
        assert!(schema["properties"]["size"].is_object());
    }

    #[tokio::test]
    async fn execute_without_key_fails_gracefully() {
        let r = tool(None).execute(serde_json::json!({ "prompt": "a cat" })).await.unwrap();
        assert!(!r.success);
        assert!(r.error.unwrap().contains("no OpenAI API key"));
    }

    #[tokio::test]
    async fn execute_requires_prompt() {
        let r = tool(Some("sk-test")).execute(serde_json::json!({})).await.unwrap();
        assert!(!r.success);
        assert!(r.error.unwrap().contains("prompt"));
    }
}
